version: "3"
services:
  app:
    build: .
    command: npm run dev-with-docker
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    ports:
      - ${PORT}:4000
      - 9229:9229

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}